# Generated by Django 2.2.10 on 2020-02-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('code', models.TextField()),
                ('product_type', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
    ]
