# Generated by Django 2.2.11 on 2020-06-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('code', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('age_limit', models.IntegerField(default=None)),
                ('age_verification', models.TextField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('avail_since', models.IntegerField(null=True)),
                ('average_rating', models.CharField(max_length=50, null=True)),
                ('base_price', models.DecimalField(decimal_places=6, max_digits=15, null=True)),
                ('buy_now_url', models.CharField(default=None, max_length=50)),
                ('company_id', models.IntegerField(default=None)),
                ('details_layout', models.CharField(default=None, max_length=50)),
                ('discount', models.CharField(default=None, max_length=50, null=True)),
                ('discount_prc', models.CharField(default=None, max_length=50, null=True)),
                ('discussion_thread_id', models.CharField(default=None, max_length=50)),
                ('discussion_type', models.CharField(default=None, max_length=50)),
                ('edp_shipping', models.CharField(default=None, max_length=50)),
                ('exceptions_type', models.CharField(default=None, max_length=50)),
                ('facebook_obj_type', models.CharField(default=None, max_length=50)),
                ('free_shipping', models.CharField(default=None, max_length=50)),
                ('has_options', models.CharField(default=None, max_length=50)),
                ('height', models.CharField(default=None, max_length=50)),
                ('is_edp', models.CharField(default=None, max_length=50)),
                ('is_op', models.CharField(default=None, max_length=50)),
                ('is_oper', models.CharField(default=None, max_length=50)),
                ('is_pbp', models.CharField(default=None, max_length=50)),
                ('is_returnable', models.CharField(default=None, max_length=50)),
                ('length', models.CharField(default=None, max_length=50)),
                ('list_price', models.DecimalField(decimal_places=6, default=None, max_digits=15)),
                ('list_qty_count', models.CharField(default=None, max_length=50)),
                ('localization', models.CharField(default=None, max_length=50)),
                ('low_avail_limit', models.CharField(default=None, max_length=50)),
                ('main_category', models.CharField(default=None, max_length=50)),
                ('max_qty', models.CharField(default=None, max_length=50)),
                ('min_qty', models.CharField(default=None, max_length=50)),
                ('options_type', models.CharField(default=None, max_length=50)),
                ('out_of_stock_actions', models.CharField(default=None, max_length=50)),
                ('price', models.CharField(default=None, max_length=50)),
                ('product', models.CharField(default=None, max_length=50)),
                ('product_code', models.CharField(default=None, max_length=50)),
                ('product_options', models.CharField(default=None, max_length=50)),
                ('list_discount', models.IntegerField(null=True)),
                ('list_discount_prc', models.CharField(max_length=50, null=True)),
                ('qty_step', models.CharField(default=None, max_length=50)),
                ('return_period', models.CharField(default=None, max_length=50)),
                ('selected_options', models.CharField(default=None, max_length=50)),
                ('seo_name', models.CharField(default=None, max_length=50)),
                ('seo_path', models.CharField(default=None, max_length=50)),
                ('shipping_freight', models.CharField(default=None, max_length=50)),
                ('shipping_params', models.CharField(default=None, max_length=50)),
                ('tax_ids', models.CharField(default=None, max_length=50)),
                ('taxed_list_price', models.CharField(max_length=50, null=True)),
                ('taxed_original_price', models.CharField(max_length=50, null=True)),
                ('timestamp', models.CharField(default=None, max_length=50)),
                ('tracking', models.CharField(default=None, max_length=50)),
                ('unlimited_download', models.CharField(default=None, max_length=50)),
                ('usergroup_ids', models.CharField(default=None, max_length=50)),
                ('weight', models.CharField(default=None, max_length=50)),
                ('width', models.CharField(default=None, max_length=50)),
                ('zero_price_action', models.CharField(default=None, max_length=50)),
                ('updated_timestamp', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
