# Generated by Django 2.2.11 on 2020-03-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200327_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='list_discount',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='list_discount_prc',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(null=True),
        ),
    ]
