# Generated by Django 2.2.11 on 2020-03-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200330_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='list_discount',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='list_discount_prc',
            field=models.TextField(default=None, null=True),
        ),
    ]
