# Generated by Django 2.2.10 on 2020-02-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200218_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='age_veryfication',
            new_name='age_verification',
        ),
    ]
