# Generated by Django 2.2.11 on 2020-03-22 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200216_1219'),
        ('api', '0005_auto_20200311_0720'),
    ]

    operations = [
    ]
