# Generated by Django 2.2.11 on 2020-03-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20200322_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_ids',
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_prc',
            field=models.TextField(default=None, null=True),
        ),
    ]
