# Generated by Django 2.2.11 on 2020-03-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200330_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='taxed_original_price',
            field=models.TextField(default=None, null=True),
        ),
    ]
