# Generated by Django 2.2.11 on 2020-03-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200322_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_pairs',
        ),
    ]
